import {
  IconAlertTriangle,
  IconArrowRight,
  IconArrowsExchange,
  IconAdjustments,
  IconBuilding,
  IconBuildingFactory,
  IconCategory,
  IconChartBar,
  IconChartPie,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconFilter,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLayoutList,
  IconListCheck,
  IconLoader2,
  IconLogin,
  IconShoppingBag,
  IconShoppingCart,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconStack,
  IconSun,
  IconTable,
  IconTrash,
  IconBrandTwitter,
  IconTruck,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUsers,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconLayoutGrid,
  IconHierarchy,
  IconPhone,
  // Inventory icons
  IconBuildingWarehouse,
  IconPackage,
  IconReceipt,
  IconTruckDelivery,
  IconClipboardList,
  IconScale,
  IconChefHat,
  IconTransfer,
  IconFileInvoice,
  IconBoxSeam,
  IconReportAnalytics,
} from '@tabler/icons-react'

import type { IconProps } from '@tabler/icons-react'

export type Icon = React.ComponentType<IconProps>

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  plus: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  layoutGrid: IconLayoutGrid,
  hierarchy: IconHierarchy,
  // Menu icons
  category: IconCategory,
  adjustments: IconAdjustments,
  // Organization icons
  building: IconBuilding,
  // Analytics icons
  chartBar: IconChartBar,
  chartPie: IconChartPie,
  filter: IconFilter,
  table: IconTable,
  list: IconLayoutList,
  shoppingBag: IconShoppingBag,
  shoppingCart: IconShoppingCart,
  truck: IconTruck,
  users: IconUsers,
  // Inventory icons
  warehouse: IconBuildingWarehouse,
  package: IconPackage,
  receipt: IconReceipt,
  truckDelivery: IconTruckDelivery,
  clipboardList: IconClipboardList,
  scale: IconScale,
  chefHat: IconChefHat,
  transfer: IconTransfer,
  fileInvoice: IconFileInvoice,
  boxSeam: IconBoxSeam,
  reportAnalytics: IconReportAnalytics,
  phone: IconPhone,
  stack: IconStack,
  arrowsExchange: IconArrowsExchange,
  listCheck: IconListCheck,
  buildingFactory: IconBuildingFactory,
}
