/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffInviteRouteImport } from './routes/staff-invite'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStaffInviteRouteImport } from './routes/onboarding/staff-invite'
import { Route as OnboardingMenuTemplateRouteImport } from './routes/onboarding/menu-template'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as OnboardingBusinessInfoRouteImport } from './routes/onboarding/business-info'
import { Route as OnboardingBranchSetupRouteImport } from './routes/onboarding/branch-setup'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardLayoutRouteRouteImport } from './routes/dashboard/_layout/route'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutViewsIndexRouteImport } from './routes/dashboard/_layout/views/index'
import { Route as DashboardLayoutStaffIndexRouteImport } from './routes/dashboard/_layout/staff/index'
import { Route as DashboardLayoutSettingsIndexRouteImport } from './routes/dashboard/_layout/settings/index'
import { Route as DashboardLayoutProfileIndexRouteImport } from './routes/dashboard/_layout/profile/index'
import { Route as DashboardLayoutOverviewIndexRouteImport } from './routes/dashboard/_layout/overview/index'
import { Route as DashboardLayoutMenuIndexRouteImport } from './routes/dashboard/_layout/menu/index'
import { Route as DashboardLayoutInventoryIndexRouteImport } from './routes/dashboard/_layout/inventory/index'
import { Route as DashboardLayoutHallsIndexRouteImport } from './routes/dashboard/_layout/halls/index'
import { Route as DashboardLayoutBranchesIndexRouteImport } from './routes/dashboard/_layout/branches/index'
import { Route as DashboardLayoutAnalyticsIndexRouteImport } from './routes/dashboard/_layout/analytics/index'
import { Route as DashboardLayoutViewsNewRouteImport } from './routes/dashboard/_layout/views/new'
import { Route as DashboardLayoutViewsViewIdRouteImport } from './routes/dashboard/_layout/views/$viewId'
import { Route as DashboardLayoutStaffEmployeesRouteImport } from './routes/dashboard/_layout/staff/employees'
import { Route as DashboardLayoutMenuModifiersRouteImport } from './routes/dashboard/_layout/menu/modifiers'
import { Route as DashboardLayoutMenuCategoriesRouteImport } from './routes/dashboard/_layout/menu/categories'
import { Route as DashboardLayoutMenuBranchOverridesRouteImport } from './routes/dashboard/_layout/menu/branch-overrides'
import { Route as DashboardLayoutMenuAdditionsRouteImport } from './routes/dashboard/_layout/menu/additions'
import { Route as DashboardLayoutBranchesBulkImportRouteImport } from './routes/dashboard/_layout/branches/bulk-import'
import { Route as DashboardLayoutBranchesBranchIdRouteImport } from './routes/dashboard/_layout/branches/$branchId'
import { Route as DashboardLayoutAnalyticsStaffRouteImport } from './routes/dashboard/_layout/analytics/staff'
import { Route as DashboardLayoutAnalyticsSalesRouteImport } from './routes/dashboard/_layout/analytics/sales'
import { Route as DashboardLayoutAnalyticsProductsRouteImport } from './routes/dashboard/_layout/analytics/products'
import { Route as DashboardLayoutAnalyticsPaymentsRouteImport } from './routes/dashboard/_layout/analytics/payments'
import { Route as DashboardLayoutAnalyticsHeatmapRouteImport } from './routes/dashboard/_layout/analytics/heatmap'
import { Route as DashboardLayoutAnalyticsForecastingRouteImport } from './routes/dashboard/_layout/analytics/forecasting'
import { Route as DashboardLayoutAnalyticsFinancialRouteImport } from './routes/dashboard/_layout/analytics/financial'
import { Route as DashboardLayoutAnalyticsCustomersRouteImport } from './routes/dashboard/_layout/analytics/customers'
import { Route as DashboardLayoutAnalyticsChannelsRouteImport } from './routes/dashboard/_layout/analytics/channels'
import { Route as DashboardLayoutAnalyticsCategoriesRouteImport } from './routes/dashboard/_layout/analytics/categories'
import { Route as DashboardLayoutAnalyticsBranchesRouteImport } from './routes/dashboard/_layout/analytics/branches'
import { Route as DashboardLayoutAnalyticsAlertsRouteImport } from './routes/dashboard/_layout/analytics/alerts'
import { Route as DashboardLayoutMenuProductsIndexRouteImport } from './routes/dashboard/_layout/menu/products/index'
import { Route as DashboardLayoutInventoryWriteoffsIndexRouteImport } from './routes/dashboard/_layout/inventory/writeoffs/index'
import { Route as DashboardLayoutInventoryWarehousesIndexRouteImport } from './routes/dashboard/_layout/inventory/warehouses/index'
import { Route as DashboardLayoutInventorySuppliersIndexRouteImport } from './routes/dashboard/_layout/inventory/suppliers/index'
import { Route as DashboardLayoutInventoryStockIndexRouteImport } from './routes/dashboard/_layout/inventory/stock/index'
import { Route as DashboardLayoutInventoryRecipesIndexRouteImport } from './routes/dashboard/_layout/inventory/recipes/index'
import { Route as DashboardLayoutInventoryPurchaseOrdersIndexRouteImport } from './routes/dashboard/_layout/inventory/purchase-orders/index'
import { Route as DashboardLayoutInventoryProductionIndexRouteImport } from './routes/dashboard/_layout/inventory/production/index'
import { Route as DashboardLayoutInventoryMovementsIndexRouteImport } from './routes/dashboard/_layout/inventory/movements/index'
import { Route as DashboardLayoutInventoryItemsIndexRouteImport } from './routes/dashboard/_layout/inventory/items/index'
import { Route as DashboardLayoutInventoryCountsIndexRouteImport } from './routes/dashboard/_layout/inventory/counts/index'
import { Route as DashboardLayoutInventoryAlertsIndexRouteImport } from './routes/dashboard/_layout/inventory/alerts/index'
import { Route as DashboardLayoutMenuProductsCreateRouteImport } from './routes/dashboard/_layout/menu/products/create'
import { Route as DashboardLayoutInventoryWriteoffsWriteoffIdRouteImport } from './routes/dashboard/_layout/inventory/writeoffs/$writeoffId'
import { Route as DashboardLayoutInventorySuppliersSupplierIdRouteImport } from './routes/dashboard/_layout/inventory/suppliers/$supplierId'
import { Route as DashboardLayoutInventoryRecipesRecipeIdRouteImport } from './routes/dashboard/_layout/inventory/recipes/$recipeId'
import { Route as DashboardLayoutInventoryPurchaseOrdersOrderIdRouteImport } from './routes/dashboard/_layout/inventory/purchase-orders/$orderId'
import { Route as DashboardLayoutInventoryProductionProductionIdRouteImport } from './routes/dashboard/_layout/inventory/production/$productionId'
import { Route as DashboardLayoutInventoryItemsItemIdRouteImport } from './routes/dashboard/_layout/inventory/items/$itemId'
import { Route as DashboardLayoutInventoryCountsCountIdRouteImport } from './routes/dashboard/_layout/inventory/counts/$countId'
import { Route as DashboardLayoutHallsHallIdFloorPlanRouteImport } from './routes/dashboard/_layout/halls/$hallId.floor-plan'
import { Route as DashboardLayoutMenuProductsProductIdEditRouteImport } from './routes/dashboard/_layout/menu/products/$productId.edit'
import { Route as DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRouteImport } from './routes/dashboard/_layout/inventory/purchase-orders/$orderId.receive'

const StaffInviteRoute = StaffInviteRouteImport.update({
  id: '/staff-invite',
  path: '/staff-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStaffInviteRoute = OnboardingStaffInviteRouteImport.update({
  id: '/onboarding/staff-invite',
  path: '/onboarding/staff-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMenuTemplateRoute = OnboardingMenuTemplateRouteImport.update({
  id: '/onboarding/menu-template',
  path: '/onboarding/menu-template',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBusinessInfoRoute = OnboardingBusinessInfoRouteImport.update({
  id: '/onboarding/business-info',
  path: '/onboarding/business-info',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBranchSetupRoute = OnboardingBranchSetupRouteImport.update({
  id: '/onboarding/branch-setup',
  path: '/onboarding/branch-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)
const DashboardLayoutViewsIndexRoute =
  DashboardLayoutViewsIndexRouteImport.update({
    id: '/views/',
    path: '/views/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutStaffIndexRoute =
  DashboardLayoutStaffIndexRouteImport.update({
    id: '/staff/',
    path: '/staff/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutSettingsIndexRoute =
  DashboardLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutProfileIndexRoute =
  DashboardLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutOverviewIndexRoute =
  DashboardLayoutOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMenuIndexRoute =
  DashboardLayoutMenuIndexRouteImport.update({
    id: '/menu/',
    path: '/menu/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryIndexRoute =
  DashboardLayoutInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutHallsIndexRoute =
  DashboardLayoutHallsIndexRouteImport.update({
    id: '/halls/',
    path: '/halls/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutBranchesIndexRoute =
  DashboardLayoutBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsIndexRoute =
  DashboardLayoutAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutViewsNewRoute = DashboardLayoutViewsNewRouteImport.update({
  id: '/views/new',
  path: '/views/new',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)
const DashboardLayoutViewsViewIdRoute =
  DashboardLayoutViewsViewIdRouteImport.update({
    id: '/views/$viewId',
    path: '/views/$viewId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutStaffEmployeesRoute =
  DashboardLayoutStaffEmployeesRouteImport.update({
    id: '/staff/employees',
    path: '/staff/employees',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMenuModifiersRoute =
  DashboardLayoutMenuModifiersRouteImport.update({
    id: '/menu/modifiers',
    path: '/menu/modifiers',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMenuCategoriesRoute =
  DashboardLayoutMenuCategoriesRouteImport.update({
    id: '/menu/categories',
    path: '/menu/categories',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMenuBranchOverridesRoute =
  DashboardLayoutMenuBranchOverridesRouteImport.update({
    id: '/menu/branch-overrides',
    path: '/menu/branch-overrides',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMenuAdditionsRoute =
  DashboardLayoutMenuAdditionsRouteImport.update({
    id: '/menu/additions',
    path: '/menu/additions',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutBranchesBulkImportRoute =
  DashboardLayoutBranchesBulkImportRouteImport.update({
    id: '/branches/bulk-import',
    path: '/branches/bulk-import',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutBranchesBranchIdRoute =
  DashboardLayoutBranchesBranchIdRouteImport.update({
    id: '/branches/$branchId',
    path: '/branches/$branchId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsStaffRoute =
  DashboardLayoutAnalyticsStaffRouteImport.update({
    id: '/analytics/staff',
    path: '/analytics/staff',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsSalesRoute =
  DashboardLayoutAnalyticsSalesRouteImport.update({
    id: '/analytics/sales',
    path: '/analytics/sales',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsProductsRoute =
  DashboardLayoutAnalyticsProductsRouteImport.update({
    id: '/analytics/products',
    path: '/analytics/products',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsPaymentsRoute =
  DashboardLayoutAnalyticsPaymentsRouteImport.update({
    id: '/analytics/payments',
    path: '/analytics/payments',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsHeatmapRoute =
  DashboardLayoutAnalyticsHeatmapRouteImport.update({
    id: '/analytics/heatmap',
    path: '/analytics/heatmap',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsForecastingRoute =
  DashboardLayoutAnalyticsForecastingRouteImport.update({
    id: '/analytics/forecasting',
    path: '/analytics/forecasting',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsFinancialRoute =
  DashboardLayoutAnalyticsFinancialRouteImport.update({
    id: '/analytics/financial',
    path: '/analytics/financial',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsCustomersRoute =
  DashboardLayoutAnalyticsCustomersRouteImport.update({
    id: '/analytics/customers',
    path: '/analytics/customers',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsChannelsRoute =
  DashboardLayoutAnalyticsChannelsRouteImport.update({
    id: '/analytics/channels',
    path: '/analytics/channels',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsCategoriesRoute =
  DashboardLayoutAnalyticsCategoriesRouteImport.update({
    id: '/analytics/categories',
    path: '/analytics/categories',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsBranchesRoute =
  DashboardLayoutAnalyticsBranchesRouteImport.update({
    id: '/analytics/branches',
    path: '/analytics/branches',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAnalyticsAlertsRoute =
  DashboardLayoutAnalyticsAlertsRouteImport.update({
    id: '/analytics/alerts',
    path: '/analytics/alerts',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMenuProductsIndexRoute =
  DashboardLayoutMenuProductsIndexRouteImport.update({
    id: '/menu/products/',
    path: '/menu/products/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryWriteoffsIndexRoute =
  DashboardLayoutInventoryWriteoffsIndexRouteImport.update({
    id: '/inventory/writeoffs/',
    path: '/inventory/writeoffs/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryWarehousesIndexRoute =
  DashboardLayoutInventoryWarehousesIndexRouteImport.update({
    id: '/inventory/warehouses/',
    path: '/inventory/warehouses/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventorySuppliersIndexRoute =
  DashboardLayoutInventorySuppliersIndexRouteImport.update({
    id: '/inventory/suppliers/',
    path: '/inventory/suppliers/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryStockIndexRoute =
  DashboardLayoutInventoryStockIndexRouteImport.update({
    id: '/inventory/stock/',
    path: '/inventory/stock/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryRecipesIndexRoute =
  DashboardLayoutInventoryRecipesIndexRouteImport.update({
    id: '/inventory/recipes/',
    path: '/inventory/recipes/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryPurchaseOrdersIndexRoute =
  DashboardLayoutInventoryPurchaseOrdersIndexRouteImport.update({
    id: '/inventory/purchase-orders/',
    path: '/inventory/purchase-orders/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryProductionIndexRoute =
  DashboardLayoutInventoryProductionIndexRouteImport.update({
    id: '/inventory/production/',
    path: '/inventory/production/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryMovementsIndexRoute =
  DashboardLayoutInventoryMovementsIndexRouteImport.update({
    id: '/inventory/movements/',
    path: '/inventory/movements/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryItemsIndexRoute =
  DashboardLayoutInventoryItemsIndexRouteImport.update({
    id: '/inventory/items/',
    path: '/inventory/items/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryCountsIndexRoute =
  DashboardLayoutInventoryCountsIndexRouteImport.update({
    id: '/inventory/counts/',
    path: '/inventory/counts/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryAlertsIndexRoute =
  DashboardLayoutInventoryAlertsIndexRouteImport.update({
    id: '/inventory/alerts/',
    path: '/inventory/alerts/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMenuProductsCreateRoute =
  DashboardLayoutMenuProductsCreateRouteImport.update({
    id: '/menu/products/create',
    path: '/menu/products/create',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryWriteoffsWriteoffIdRoute =
  DashboardLayoutInventoryWriteoffsWriteoffIdRouteImport.update({
    id: '/inventory/writeoffs/$writeoffId',
    path: '/inventory/writeoffs/$writeoffId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventorySuppliersSupplierIdRoute =
  DashboardLayoutInventorySuppliersSupplierIdRouteImport.update({
    id: '/inventory/suppliers/$supplierId',
    path: '/inventory/suppliers/$supplierId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryRecipesRecipeIdRoute =
  DashboardLayoutInventoryRecipesRecipeIdRouteImport.update({
    id: '/inventory/recipes/$recipeId',
    path: '/inventory/recipes/$recipeId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryPurchaseOrdersOrderIdRoute =
  DashboardLayoutInventoryPurchaseOrdersOrderIdRouteImport.update({
    id: '/inventory/purchase-orders/$orderId',
    path: '/inventory/purchase-orders/$orderId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryProductionProductionIdRoute =
  DashboardLayoutInventoryProductionProductionIdRouteImport.update({
    id: '/inventory/production/$productionId',
    path: '/inventory/production/$productionId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryItemsItemIdRoute =
  DashboardLayoutInventoryItemsItemIdRouteImport.update({
    id: '/inventory/items/$itemId',
    path: '/inventory/items/$itemId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryCountsCountIdRoute =
  DashboardLayoutInventoryCountsCountIdRouteImport.update({
    id: '/inventory/counts/$countId',
    path: '/inventory/counts/$countId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutHallsHallIdFloorPlanRoute =
  DashboardLayoutHallsHallIdFloorPlanRouteImport.update({
    id: '/halls/$hallId/floor-plan',
    path: '/halls/$hallId/floor-plan',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMenuProductsProductIdEditRoute =
  DashboardLayoutMenuProductsProductIdEditRouteImport.update({
    id: '/menu/products/$productId/edit',
    path: '/menu/products/$productId/edit',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRoute =
  DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRouteImport.update({
    id: '/receive',
    path: '/receive',
    getParentRoute: () => DashboardLayoutInventoryPurchaseOrdersOrderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/staff-invite': typeof StaffInviteRoute
  '/dashboard': typeof DashboardLayoutRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/onboarding/branch-setup': typeof OnboardingBranchSetupRoute
  '/onboarding/business-info': typeof OnboardingBusinessInfoRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/menu-template': typeof OnboardingMenuTemplateRoute
  '/onboarding/staff-invite': typeof OnboardingStaffInviteRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/analytics/alerts': typeof DashboardLayoutAnalyticsAlertsRoute
  '/dashboard/analytics/branches': typeof DashboardLayoutAnalyticsBranchesRoute
  '/dashboard/analytics/categories': typeof DashboardLayoutAnalyticsCategoriesRoute
  '/dashboard/analytics/channels': typeof DashboardLayoutAnalyticsChannelsRoute
  '/dashboard/analytics/customers': typeof DashboardLayoutAnalyticsCustomersRoute
  '/dashboard/analytics/financial': typeof DashboardLayoutAnalyticsFinancialRoute
  '/dashboard/analytics/forecasting': typeof DashboardLayoutAnalyticsForecastingRoute
  '/dashboard/analytics/heatmap': typeof DashboardLayoutAnalyticsHeatmapRoute
  '/dashboard/analytics/payments': typeof DashboardLayoutAnalyticsPaymentsRoute
  '/dashboard/analytics/products': typeof DashboardLayoutAnalyticsProductsRoute
  '/dashboard/analytics/sales': typeof DashboardLayoutAnalyticsSalesRoute
  '/dashboard/analytics/staff': typeof DashboardLayoutAnalyticsStaffRoute
  '/dashboard/branches/$branchId': typeof DashboardLayoutBranchesBranchIdRoute
  '/dashboard/branches/bulk-import': typeof DashboardLayoutBranchesBulkImportRoute
  '/dashboard/menu/additions': typeof DashboardLayoutMenuAdditionsRoute
  '/dashboard/menu/branch-overrides': typeof DashboardLayoutMenuBranchOverridesRoute
  '/dashboard/menu/categories': typeof DashboardLayoutMenuCategoriesRoute
  '/dashboard/menu/modifiers': typeof DashboardLayoutMenuModifiersRoute
  '/dashboard/staff/employees': typeof DashboardLayoutStaffEmployeesRoute
  '/dashboard/views/$viewId': typeof DashboardLayoutViewsViewIdRoute
  '/dashboard/views/new': typeof DashboardLayoutViewsNewRoute
  '/dashboard/analytics/': typeof DashboardLayoutAnalyticsIndexRoute
  '/dashboard/branches/': typeof DashboardLayoutBranchesIndexRoute
  '/dashboard/halls/': typeof DashboardLayoutHallsIndexRoute
  '/dashboard/inventory/': typeof DashboardLayoutInventoryIndexRoute
  '/dashboard/menu/': typeof DashboardLayoutMenuIndexRoute
  '/dashboard/overview/': typeof DashboardLayoutOverviewIndexRoute
  '/dashboard/profile/': typeof DashboardLayoutProfileIndexRoute
  '/dashboard/settings/': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/staff/': typeof DashboardLayoutStaffIndexRoute
  '/dashboard/views/': typeof DashboardLayoutViewsIndexRoute
  '/dashboard/halls/$hallId/floor-plan': typeof DashboardLayoutHallsHallIdFloorPlanRoute
  '/dashboard/inventory/counts/$countId': typeof DashboardLayoutInventoryCountsCountIdRoute
  '/dashboard/inventory/items/$itemId': typeof DashboardLayoutInventoryItemsItemIdRoute
  '/dashboard/inventory/production/$productionId': typeof DashboardLayoutInventoryProductionProductionIdRoute
  '/dashboard/inventory/purchase-orders/$orderId': typeof DashboardLayoutInventoryPurchaseOrdersOrderIdRouteWithChildren
  '/dashboard/inventory/recipes/$recipeId': typeof DashboardLayoutInventoryRecipesRecipeIdRoute
  '/dashboard/inventory/suppliers/$supplierId': typeof DashboardLayoutInventorySuppliersSupplierIdRoute
  '/dashboard/inventory/writeoffs/$writeoffId': typeof DashboardLayoutInventoryWriteoffsWriteoffIdRoute
  '/dashboard/menu/products/create': typeof DashboardLayoutMenuProductsCreateRoute
  '/dashboard/inventory/alerts/': typeof DashboardLayoutInventoryAlertsIndexRoute
  '/dashboard/inventory/counts/': typeof DashboardLayoutInventoryCountsIndexRoute
  '/dashboard/inventory/items/': typeof DashboardLayoutInventoryItemsIndexRoute
  '/dashboard/inventory/movements/': typeof DashboardLayoutInventoryMovementsIndexRoute
  '/dashboard/inventory/production/': typeof DashboardLayoutInventoryProductionIndexRoute
  '/dashboard/inventory/purchase-orders/': typeof DashboardLayoutInventoryPurchaseOrdersIndexRoute
  '/dashboard/inventory/recipes/': typeof DashboardLayoutInventoryRecipesIndexRoute
  '/dashboard/inventory/stock/': typeof DashboardLayoutInventoryStockIndexRoute
  '/dashboard/inventory/suppliers/': typeof DashboardLayoutInventorySuppliersIndexRoute
  '/dashboard/inventory/warehouses/': typeof DashboardLayoutInventoryWarehousesIndexRoute
  '/dashboard/inventory/writeoffs/': typeof DashboardLayoutInventoryWriteoffsIndexRoute
  '/dashboard/menu/products/': typeof DashboardLayoutMenuProductsIndexRoute
  '/dashboard/inventory/purchase-orders/$orderId/receive': typeof DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRoute
  '/dashboard/menu/products/$productId/edit': typeof DashboardLayoutMenuProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/staff-invite': typeof StaffInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/onboarding/branch-setup': typeof OnboardingBranchSetupRoute
  '/onboarding/business-info': typeof OnboardingBusinessInfoRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/menu-template': typeof OnboardingMenuTemplateRoute
  '/onboarding/staff-invite': typeof OnboardingStaffInviteRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/analytics/alerts': typeof DashboardLayoutAnalyticsAlertsRoute
  '/dashboard/analytics/branches': typeof DashboardLayoutAnalyticsBranchesRoute
  '/dashboard/analytics/categories': typeof DashboardLayoutAnalyticsCategoriesRoute
  '/dashboard/analytics/channels': typeof DashboardLayoutAnalyticsChannelsRoute
  '/dashboard/analytics/customers': typeof DashboardLayoutAnalyticsCustomersRoute
  '/dashboard/analytics/financial': typeof DashboardLayoutAnalyticsFinancialRoute
  '/dashboard/analytics/forecasting': typeof DashboardLayoutAnalyticsForecastingRoute
  '/dashboard/analytics/heatmap': typeof DashboardLayoutAnalyticsHeatmapRoute
  '/dashboard/analytics/payments': typeof DashboardLayoutAnalyticsPaymentsRoute
  '/dashboard/analytics/products': typeof DashboardLayoutAnalyticsProductsRoute
  '/dashboard/analytics/sales': typeof DashboardLayoutAnalyticsSalesRoute
  '/dashboard/analytics/staff': typeof DashboardLayoutAnalyticsStaffRoute
  '/dashboard/branches/$branchId': typeof DashboardLayoutBranchesBranchIdRoute
  '/dashboard/branches/bulk-import': typeof DashboardLayoutBranchesBulkImportRoute
  '/dashboard/menu/additions': typeof DashboardLayoutMenuAdditionsRoute
  '/dashboard/menu/branch-overrides': typeof DashboardLayoutMenuBranchOverridesRoute
  '/dashboard/menu/categories': typeof DashboardLayoutMenuCategoriesRoute
  '/dashboard/menu/modifiers': typeof DashboardLayoutMenuModifiersRoute
  '/dashboard/staff/employees': typeof DashboardLayoutStaffEmployeesRoute
  '/dashboard/views/$viewId': typeof DashboardLayoutViewsViewIdRoute
  '/dashboard/views/new': typeof DashboardLayoutViewsNewRoute
  '/dashboard/analytics': typeof DashboardLayoutAnalyticsIndexRoute
  '/dashboard/branches': typeof DashboardLayoutBranchesIndexRoute
  '/dashboard/halls': typeof DashboardLayoutHallsIndexRoute
  '/dashboard/inventory': typeof DashboardLayoutInventoryIndexRoute
  '/dashboard/menu': typeof DashboardLayoutMenuIndexRoute
  '/dashboard/overview': typeof DashboardLayoutOverviewIndexRoute
  '/dashboard/profile': typeof DashboardLayoutProfileIndexRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/staff': typeof DashboardLayoutStaffIndexRoute
  '/dashboard/views': typeof DashboardLayoutViewsIndexRoute
  '/dashboard/halls/$hallId/floor-plan': typeof DashboardLayoutHallsHallIdFloorPlanRoute
  '/dashboard/inventory/counts/$countId': typeof DashboardLayoutInventoryCountsCountIdRoute
  '/dashboard/inventory/items/$itemId': typeof DashboardLayoutInventoryItemsItemIdRoute
  '/dashboard/inventory/production/$productionId': typeof DashboardLayoutInventoryProductionProductionIdRoute
  '/dashboard/inventory/purchase-orders/$orderId': typeof DashboardLayoutInventoryPurchaseOrdersOrderIdRouteWithChildren
  '/dashboard/inventory/recipes/$recipeId': typeof DashboardLayoutInventoryRecipesRecipeIdRoute
  '/dashboard/inventory/suppliers/$supplierId': typeof DashboardLayoutInventorySuppliersSupplierIdRoute
  '/dashboard/inventory/writeoffs/$writeoffId': typeof DashboardLayoutInventoryWriteoffsWriteoffIdRoute
  '/dashboard/menu/products/create': typeof DashboardLayoutMenuProductsCreateRoute
  '/dashboard/inventory/alerts': typeof DashboardLayoutInventoryAlertsIndexRoute
  '/dashboard/inventory/counts': typeof DashboardLayoutInventoryCountsIndexRoute
  '/dashboard/inventory/items': typeof DashboardLayoutInventoryItemsIndexRoute
  '/dashboard/inventory/movements': typeof DashboardLayoutInventoryMovementsIndexRoute
  '/dashboard/inventory/production': typeof DashboardLayoutInventoryProductionIndexRoute
  '/dashboard/inventory/purchase-orders': typeof DashboardLayoutInventoryPurchaseOrdersIndexRoute
  '/dashboard/inventory/recipes': typeof DashboardLayoutInventoryRecipesIndexRoute
  '/dashboard/inventory/stock': typeof DashboardLayoutInventoryStockIndexRoute
  '/dashboard/inventory/suppliers': typeof DashboardLayoutInventorySuppliersIndexRoute
  '/dashboard/inventory/warehouses': typeof DashboardLayoutInventoryWarehousesIndexRoute
  '/dashboard/inventory/writeoffs': typeof DashboardLayoutInventoryWriteoffsIndexRoute
  '/dashboard/menu/products': typeof DashboardLayoutMenuProductsIndexRoute
  '/dashboard/inventory/purchase-orders/$orderId/receive': typeof DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRoute
  '/dashboard/menu/products/$productId/edit': typeof DashboardLayoutMenuProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/staff-invite': typeof StaffInviteRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/onboarding/branch-setup': typeof OnboardingBranchSetupRoute
  '/onboarding/business-info': typeof OnboardingBusinessInfoRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/menu-template': typeof OnboardingMenuTemplateRoute
  '/onboarding/staff-invite': typeof OnboardingStaffInviteRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/analytics/alerts': typeof DashboardLayoutAnalyticsAlertsRoute
  '/dashboard/_layout/analytics/branches': typeof DashboardLayoutAnalyticsBranchesRoute
  '/dashboard/_layout/analytics/categories': typeof DashboardLayoutAnalyticsCategoriesRoute
  '/dashboard/_layout/analytics/channels': typeof DashboardLayoutAnalyticsChannelsRoute
  '/dashboard/_layout/analytics/customers': typeof DashboardLayoutAnalyticsCustomersRoute
  '/dashboard/_layout/analytics/financial': typeof DashboardLayoutAnalyticsFinancialRoute
  '/dashboard/_layout/analytics/forecasting': typeof DashboardLayoutAnalyticsForecastingRoute
  '/dashboard/_layout/analytics/heatmap': typeof DashboardLayoutAnalyticsHeatmapRoute
  '/dashboard/_layout/analytics/payments': typeof DashboardLayoutAnalyticsPaymentsRoute
  '/dashboard/_layout/analytics/products': typeof DashboardLayoutAnalyticsProductsRoute
  '/dashboard/_layout/analytics/sales': typeof DashboardLayoutAnalyticsSalesRoute
  '/dashboard/_layout/analytics/staff': typeof DashboardLayoutAnalyticsStaffRoute
  '/dashboard/_layout/branches/$branchId': typeof DashboardLayoutBranchesBranchIdRoute
  '/dashboard/_layout/branches/bulk-import': typeof DashboardLayoutBranchesBulkImportRoute
  '/dashboard/_layout/menu/additions': typeof DashboardLayoutMenuAdditionsRoute
  '/dashboard/_layout/menu/branch-overrides': typeof DashboardLayoutMenuBranchOverridesRoute
  '/dashboard/_layout/menu/categories': typeof DashboardLayoutMenuCategoriesRoute
  '/dashboard/_layout/menu/modifiers': typeof DashboardLayoutMenuModifiersRoute
  '/dashboard/_layout/staff/employees': typeof DashboardLayoutStaffEmployeesRoute
  '/dashboard/_layout/views/$viewId': typeof DashboardLayoutViewsViewIdRoute
  '/dashboard/_layout/views/new': typeof DashboardLayoutViewsNewRoute
  '/dashboard/_layout/analytics/': typeof DashboardLayoutAnalyticsIndexRoute
  '/dashboard/_layout/branches/': typeof DashboardLayoutBranchesIndexRoute
  '/dashboard/_layout/halls/': typeof DashboardLayoutHallsIndexRoute
  '/dashboard/_layout/inventory/': typeof DashboardLayoutInventoryIndexRoute
  '/dashboard/_layout/menu/': typeof DashboardLayoutMenuIndexRoute
  '/dashboard/_layout/overview/': typeof DashboardLayoutOverviewIndexRoute
  '/dashboard/_layout/profile/': typeof DashboardLayoutProfileIndexRoute
  '/dashboard/_layout/settings/': typeof DashboardLayoutSettingsIndexRoute
  '/dashboard/_layout/staff/': typeof DashboardLayoutStaffIndexRoute
  '/dashboard/_layout/views/': typeof DashboardLayoutViewsIndexRoute
  '/dashboard/_layout/halls/$hallId/floor-plan': typeof DashboardLayoutHallsHallIdFloorPlanRoute
  '/dashboard/_layout/inventory/counts/$countId': typeof DashboardLayoutInventoryCountsCountIdRoute
  '/dashboard/_layout/inventory/items/$itemId': typeof DashboardLayoutInventoryItemsItemIdRoute
  '/dashboard/_layout/inventory/production/$productionId': typeof DashboardLayoutInventoryProductionProductionIdRoute
  '/dashboard/_layout/inventory/purchase-orders/$orderId': typeof DashboardLayoutInventoryPurchaseOrdersOrderIdRouteWithChildren
  '/dashboard/_layout/inventory/recipes/$recipeId': typeof DashboardLayoutInventoryRecipesRecipeIdRoute
  '/dashboard/_layout/inventory/suppliers/$supplierId': typeof DashboardLayoutInventorySuppliersSupplierIdRoute
  '/dashboard/_layout/inventory/writeoffs/$writeoffId': typeof DashboardLayoutInventoryWriteoffsWriteoffIdRoute
  '/dashboard/_layout/menu/products/create': typeof DashboardLayoutMenuProductsCreateRoute
  '/dashboard/_layout/inventory/alerts/': typeof DashboardLayoutInventoryAlertsIndexRoute
  '/dashboard/_layout/inventory/counts/': typeof DashboardLayoutInventoryCountsIndexRoute
  '/dashboard/_layout/inventory/items/': typeof DashboardLayoutInventoryItemsIndexRoute
  '/dashboard/_layout/inventory/movements/': typeof DashboardLayoutInventoryMovementsIndexRoute
  '/dashboard/_layout/inventory/production/': typeof DashboardLayoutInventoryProductionIndexRoute
  '/dashboard/_layout/inventory/purchase-orders/': typeof DashboardLayoutInventoryPurchaseOrdersIndexRoute
  '/dashboard/_layout/inventory/recipes/': typeof DashboardLayoutInventoryRecipesIndexRoute
  '/dashboard/_layout/inventory/stock/': typeof DashboardLayoutInventoryStockIndexRoute
  '/dashboard/_layout/inventory/suppliers/': typeof DashboardLayoutInventorySuppliersIndexRoute
  '/dashboard/_layout/inventory/warehouses/': typeof DashboardLayoutInventoryWarehousesIndexRoute
  '/dashboard/_layout/inventory/writeoffs/': typeof DashboardLayoutInventoryWriteoffsIndexRoute
  '/dashboard/_layout/menu/products/': typeof DashboardLayoutMenuProductsIndexRoute
  '/dashboard/_layout/inventory/purchase-orders/$orderId/receive': typeof DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRoute
  '/dashboard/_layout/menu/products/$productId/edit': typeof DashboardLayoutMenuProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/staff-invite'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/onboarding/branch-setup'
    | '/onboarding/business-info'
    | '/onboarding/complete'
    | '/onboarding/menu-template'
    | '/onboarding/staff-invite'
    | '/dashboard/'
    | '/dashboard/analytics/alerts'
    | '/dashboard/analytics/branches'
    | '/dashboard/analytics/categories'
    | '/dashboard/analytics/channels'
    | '/dashboard/analytics/customers'
    | '/dashboard/analytics/financial'
    | '/dashboard/analytics/forecasting'
    | '/dashboard/analytics/heatmap'
    | '/dashboard/analytics/payments'
    | '/dashboard/analytics/products'
    | '/dashboard/analytics/sales'
    | '/dashboard/analytics/staff'
    | '/dashboard/branches/$branchId'
    | '/dashboard/branches/bulk-import'
    | '/dashboard/menu/additions'
    | '/dashboard/menu/branch-overrides'
    | '/dashboard/menu/categories'
    | '/dashboard/menu/modifiers'
    | '/dashboard/staff/employees'
    | '/dashboard/views/$viewId'
    | '/dashboard/views/new'
    | '/dashboard/analytics/'
    | '/dashboard/branches/'
    | '/dashboard/halls/'
    | '/dashboard/inventory/'
    | '/dashboard/menu/'
    | '/dashboard/overview/'
    | '/dashboard/profile/'
    | '/dashboard/settings/'
    | '/dashboard/staff/'
    | '/dashboard/views/'
    | '/dashboard/halls/$hallId/floor-plan'
    | '/dashboard/inventory/counts/$countId'
    | '/dashboard/inventory/items/$itemId'
    | '/dashboard/inventory/production/$productionId'
    | '/dashboard/inventory/purchase-orders/$orderId'
    | '/dashboard/inventory/recipes/$recipeId'
    | '/dashboard/inventory/suppliers/$supplierId'
    | '/dashboard/inventory/writeoffs/$writeoffId'
    | '/dashboard/menu/products/create'
    | '/dashboard/inventory/alerts/'
    | '/dashboard/inventory/counts/'
    | '/dashboard/inventory/items/'
    | '/dashboard/inventory/movements/'
    | '/dashboard/inventory/production/'
    | '/dashboard/inventory/purchase-orders/'
    | '/dashboard/inventory/recipes/'
    | '/dashboard/inventory/stock/'
    | '/dashboard/inventory/suppliers/'
    | '/dashboard/inventory/warehouses/'
    | '/dashboard/inventory/writeoffs/'
    | '/dashboard/menu/products/'
    | '/dashboard/inventory/purchase-orders/$orderId/receive'
    | '/dashboard/menu/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/staff-invite'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/onboarding/branch-setup'
    | '/onboarding/business-info'
    | '/onboarding/complete'
    | '/onboarding/menu-template'
    | '/onboarding/staff-invite'
    | '/dashboard'
    | '/dashboard/analytics/alerts'
    | '/dashboard/analytics/branches'
    | '/dashboard/analytics/categories'
    | '/dashboard/analytics/channels'
    | '/dashboard/analytics/customers'
    | '/dashboard/analytics/financial'
    | '/dashboard/analytics/forecasting'
    | '/dashboard/analytics/heatmap'
    | '/dashboard/analytics/payments'
    | '/dashboard/analytics/products'
    | '/dashboard/analytics/sales'
    | '/dashboard/analytics/staff'
    | '/dashboard/branches/$branchId'
    | '/dashboard/branches/bulk-import'
    | '/dashboard/menu/additions'
    | '/dashboard/menu/branch-overrides'
    | '/dashboard/menu/categories'
    | '/dashboard/menu/modifiers'
    | '/dashboard/staff/employees'
    | '/dashboard/views/$viewId'
    | '/dashboard/views/new'
    | '/dashboard/analytics'
    | '/dashboard/branches'
    | '/dashboard/halls'
    | '/dashboard/inventory'
    | '/dashboard/menu'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/views'
    | '/dashboard/halls/$hallId/floor-plan'
    | '/dashboard/inventory/counts/$countId'
    | '/dashboard/inventory/items/$itemId'
    | '/dashboard/inventory/production/$productionId'
    | '/dashboard/inventory/purchase-orders/$orderId'
    | '/dashboard/inventory/recipes/$recipeId'
    | '/dashboard/inventory/suppliers/$supplierId'
    | '/dashboard/inventory/writeoffs/$writeoffId'
    | '/dashboard/menu/products/create'
    | '/dashboard/inventory/alerts'
    | '/dashboard/inventory/counts'
    | '/dashboard/inventory/items'
    | '/dashboard/inventory/movements'
    | '/dashboard/inventory/production'
    | '/dashboard/inventory/purchase-orders'
    | '/dashboard/inventory/recipes'
    | '/dashboard/inventory/stock'
    | '/dashboard/inventory/suppliers'
    | '/dashboard/inventory/warehouses'
    | '/dashboard/inventory/writeoffs'
    | '/dashboard/menu/products'
    | '/dashboard/inventory/purchase-orders/$orderId/receive'
    | '/dashboard/menu/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/invite'
    | '/staff-invite'
    | '/dashboard/_layout'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/onboarding/branch-setup'
    | '/onboarding/business-info'
    | '/onboarding/complete'
    | '/onboarding/menu-template'
    | '/onboarding/staff-invite'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/analytics/alerts'
    | '/dashboard/_layout/analytics/branches'
    | '/dashboard/_layout/analytics/categories'
    | '/dashboard/_layout/analytics/channels'
    | '/dashboard/_layout/analytics/customers'
    | '/dashboard/_layout/analytics/financial'
    | '/dashboard/_layout/analytics/forecasting'
    | '/dashboard/_layout/analytics/heatmap'
    | '/dashboard/_layout/analytics/payments'
    | '/dashboard/_layout/analytics/products'
    | '/dashboard/_layout/analytics/sales'
    | '/dashboard/_layout/analytics/staff'
    | '/dashboard/_layout/branches/$branchId'
    | '/dashboard/_layout/branches/bulk-import'
    | '/dashboard/_layout/menu/additions'
    | '/dashboard/_layout/menu/branch-overrides'
    | '/dashboard/_layout/menu/categories'
    | '/dashboard/_layout/menu/modifiers'
    | '/dashboard/_layout/staff/employees'
    | '/dashboard/_layout/views/$viewId'
    | '/dashboard/_layout/views/new'
    | '/dashboard/_layout/analytics/'
    | '/dashboard/_layout/branches/'
    | '/dashboard/_layout/halls/'
    | '/dashboard/_layout/inventory/'
    | '/dashboard/_layout/menu/'
    | '/dashboard/_layout/overview/'
    | '/dashboard/_layout/profile/'
    | '/dashboard/_layout/settings/'
    | '/dashboard/_layout/staff/'
    | '/dashboard/_layout/views/'
    | '/dashboard/_layout/halls/$hallId/floor-plan'
    | '/dashboard/_layout/inventory/counts/$countId'
    | '/dashboard/_layout/inventory/items/$itemId'
    | '/dashboard/_layout/inventory/production/$productionId'
    | '/dashboard/_layout/inventory/purchase-orders/$orderId'
    | '/dashboard/_layout/inventory/recipes/$recipeId'
    | '/dashboard/_layout/inventory/suppliers/$supplierId'
    | '/dashboard/_layout/inventory/writeoffs/$writeoffId'
    | '/dashboard/_layout/menu/products/create'
    | '/dashboard/_layout/inventory/alerts/'
    | '/dashboard/_layout/inventory/counts/'
    | '/dashboard/_layout/inventory/items/'
    | '/dashboard/_layout/inventory/movements/'
    | '/dashboard/_layout/inventory/production/'
    | '/dashboard/_layout/inventory/purchase-orders/'
    | '/dashboard/_layout/inventory/recipes/'
    | '/dashboard/_layout/inventory/stock/'
    | '/dashboard/_layout/inventory/suppliers/'
    | '/dashboard/_layout/inventory/warehouses/'
    | '/dashboard/_layout/inventory/writeoffs/'
    | '/dashboard/_layout/menu/products/'
    | '/dashboard/_layout/inventory/purchase-orders/$orderId/receive'
    | '/dashboard/_layout/menu/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteRoute: typeof InviteRoute
  StaffInviteRoute: typeof StaffInviteRoute
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  OnboardingBranchSetupRoute: typeof OnboardingBranchSetupRoute
  OnboardingBusinessInfoRoute: typeof OnboardingBusinessInfoRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingMenuTemplateRoute: typeof OnboardingMenuTemplateRoute
  OnboardingStaffInviteRoute: typeof OnboardingStaffInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-invite': {
      id: '/staff-invite'
      path: '/staff-invite'
      fullPath: '/staff-invite'
      preLoaderRoute: typeof StaffInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/staff-invite': {
      id: '/onboarding/staff-invite'
      path: '/onboarding/staff-invite'
      fullPath: '/onboarding/staff-invite'
      preLoaderRoute: typeof OnboardingStaffInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/menu-template': {
      id: '/onboarding/menu-template'
      path: '/onboarding/menu-template'
      fullPath: '/onboarding/menu-template'
      preLoaderRoute: typeof OnboardingMenuTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/business-info': {
      id: '/onboarding/business-info'
      path: '/onboarding/business-info'
      fullPath: '/onboarding/business-info'
      preLoaderRoute: typeof OnboardingBusinessInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/branch-setup': {
      id: '/onboarding/branch-setup'
      path: '/onboarding/branch-setup'
      fullPath: '/onboarding/branch-setup'
      preLoaderRoute: typeof OnboardingBranchSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/views/': {
      id: '/dashboard/_layout/views/'
      path: '/views'
      fullPath: '/dashboard/views/'
      preLoaderRoute: typeof DashboardLayoutViewsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/staff/': {
      id: '/dashboard/_layout/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof DashboardLayoutStaffIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/settings/': {
      id: '/dashboard/_layout/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/profile/': {
      id: '/dashboard/_layout/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardLayoutProfileIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/overview/': {
      id: '/dashboard/_layout/overview/'
      path: '/overview'
      fullPath: '/dashboard/overview/'
      preLoaderRoute: typeof DashboardLayoutOverviewIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/menu/': {
      id: '/dashboard/_layout/menu/'
      path: '/menu'
      fullPath: '/dashboard/menu/'
      preLoaderRoute: typeof DashboardLayoutMenuIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/': {
      id: '/dashboard/_layout/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory/'
      preLoaderRoute: typeof DashboardLayoutInventoryIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/halls/': {
      id: '/dashboard/_layout/halls/'
      path: '/halls'
      fullPath: '/dashboard/halls/'
      preLoaderRoute: typeof DashboardLayoutHallsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/branches/': {
      id: '/dashboard/_layout/branches/'
      path: '/branches'
      fullPath: '/dashboard/branches/'
      preLoaderRoute: typeof DashboardLayoutBranchesIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/': {
      id: '/dashboard/_layout/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardLayoutAnalyticsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/views/new': {
      id: '/dashboard/_layout/views/new'
      path: '/views/new'
      fullPath: '/dashboard/views/new'
      preLoaderRoute: typeof DashboardLayoutViewsNewRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/views/$viewId': {
      id: '/dashboard/_layout/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/dashboard/views/$viewId'
      preLoaderRoute: typeof DashboardLayoutViewsViewIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/staff/employees': {
      id: '/dashboard/_layout/staff/employees'
      path: '/staff/employees'
      fullPath: '/dashboard/staff/employees'
      preLoaderRoute: typeof DashboardLayoutStaffEmployeesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/menu/modifiers': {
      id: '/dashboard/_layout/menu/modifiers'
      path: '/menu/modifiers'
      fullPath: '/dashboard/menu/modifiers'
      preLoaderRoute: typeof DashboardLayoutMenuModifiersRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/menu/categories': {
      id: '/dashboard/_layout/menu/categories'
      path: '/menu/categories'
      fullPath: '/dashboard/menu/categories'
      preLoaderRoute: typeof DashboardLayoutMenuCategoriesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/menu/branch-overrides': {
      id: '/dashboard/_layout/menu/branch-overrides'
      path: '/menu/branch-overrides'
      fullPath: '/dashboard/menu/branch-overrides'
      preLoaderRoute: typeof DashboardLayoutMenuBranchOverridesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/menu/additions': {
      id: '/dashboard/_layout/menu/additions'
      path: '/menu/additions'
      fullPath: '/dashboard/menu/additions'
      preLoaderRoute: typeof DashboardLayoutMenuAdditionsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/branches/bulk-import': {
      id: '/dashboard/_layout/branches/bulk-import'
      path: '/branches/bulk-import'
      fullPath: '/dashboard/branches/bulk-import'
      preLoaderRoute: typeof DashboardLayoutBranchesBulkImportRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/branches/$branchId': {
      id: '/dashboard/_layout/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/dashboard/branches/$branchId'
      preLoaderRoute: typeof DashboardLayoutBranchesBranchIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/staff': {
      id: '/dashboard/_layout/analytics/staff'
      path: '/analytics/staff'
      fullPath: '/dashboard/analytics/staff'
      preLoaderRoute: typeof DashboardLayoutAnalyticsStaffRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/sales': {
      id: '/dashboard/_layout/analytics/sales'
      path: '/analytics/sales'
      fullPath: '/dashboard/analytics/sales'
      preLoaderRoute: typeof DashboardLayoutAnalyticsSalesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/products': {
      id: '/dashboard/_layout/analytics/products'
      path: '/analytics/products'
      fullPath: '/dashboard/analytics/products'
      preLoaderRoute: typeof DashboardLayoutAnalyticsProductsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/payments': {
      id: '/dashboard/_layout/analytics/payments'
      path: '/analytics/payments'
      fullPath: '/dashboard/analytics/payments'
      preLoaderRoute: typeof DashboardLayoutAnalyticsPaymentsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/heatmap': {
      id: '/dashboard/_layout/analytics/heatmap'
      path: '/analytics/heatmap'
      fullPath: '/dashboard/analytics/heatmap'
      preLoaderRoute: typeof DashboardLayoutAnalyticsHeatmapRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/forecasting': {
      id: '/dashboard/_layout/analytics/forecasting'
      path: '/analytics/forecasting'
      fullPath: '/dashboard/analytics/forecasting'
      preLoaderRoute: typeof DashboardLayoutAnalyticsForecastingRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/financial': {
      id: '/dashboard/_layout/analytics/financial'
      path: '/analytics/financial'
      fullPath: '/dashboard/analytics/financial'
      preLoaderRoute: typeof DashboardLayoutAnalyticsFinancialRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/customers': {
      id: '/dashboard/_layout/analytics/customers'
      path: '/analytics/customers'
      fullPath: '/dashboard/analytics/customers'
      preLoaderRoute: typeof DashboardLayoutAnalyticsCustomersRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/channels': {
      id: '/dashboard/_layout/analytics/channels'
      path: '/analytics/channels'
      fullPath: '/dashboard/analytics/channels'
      preLoaderRoute: typeof DashboardLayoutAnalyticsChannelsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/categories': {
      id: '/dashboard/_layout/analytics/categories'
      path: '/analytics/categories'
      fullPath: '/dashboard/analytics/categories'
      preLoaderRoute: typeof DashboardLayoutAnalyticsCategoriesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/branches': {
      id: '/dashboard/_layout/analytics/branches'
      path: '/analytics/branches'
      fullPath: '/dashboard/analytics/branches'
      preLoaderRoute: typeof DashboardLayoutAnalyticsBranchesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/analytics/alerts': {
      id: '/dashboard/_layout/analytics/alerts'
      path: '/analytics/alerts'
      fullPath: '/dashboard/analytics/alerts'
      preLoaderRoute: typeof DashboardLayoutAnalyticsAlertsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/menu/products/': {
      id: '/dashboard/_layout/menu/products/'
      path: '/menu/products'
      fullPath: '/dashboard/menu/products/'
      preLoaderRoute: typeof DashboardLayoutMenuProductsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/writeoffs/': {
      id: '/dashboard/_layout/inventory/writeoffs/'
      path: '/inventory/writeoffs'
      fullPath: '/dashboard/inventory/writeoffs/'
      preLoaderRoute: typeof DashboardLayoutInventoryWriteoffsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/warehouses/': {
      id: '/dashboard/_layout/inventory/warehouses/'
      path: '/inventory/warehouses'
      fullPath: '/dashboard/inventory/warehouses/'
      preLoaderRoute: typeof DashboardLayoutInventoryWarehousesIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/suppliers/': {
      id: '/dashboard/_layout/inventory/suppliers/'
      path: '/inventory/suppliers'
      fullPath: '/dashboard/inventory/suppliers/'
      preLoaderRoute: typeof DashboardLayoutInventorySuppliersIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/stock/': {
      id: '/dashboard/_layout/inventory/stock/'
      path: '/inventory/stock'
      fullPath: '/dashboard/inventory/stock/'
      preLoaderRoute: typeof DashboardLayoutInventoryStockIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/recipes/': {
      id: '/dashboard/_layout/inventory/recipes/'
      path: '/inventory/recipes'
      fullPath: '/dashboard/inventory/recipes/'
      preLoaderRoute: typeof DashboardLayoutInventoryRecipesIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/purchase-orders/': {
      id: '/dashboard/_layout/inventory/purchase-orders/'
      path: '/inventory/purchase-orders'
      fullPath: '/dashboard/inventory/purchase-orders/'
      preLoaderRoute: typeof DashboardLayoutInventoryPurchaseOrdersIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/production/': {
      id: '/dashboard/_layout/inventory/production/'
      path: '/inventory/production'
      fullPath: '/dashboard/inventory/production/'
      preLoaderRoute: typeof DashboardLayoutInventoryProductionIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/movements/': {
      id: '/dashboard/_layout/inventory/movements/'
      path: '/inventory/movements'
      fullPath: '/dashboard/inventory/movements/'
      preLoaderRoute: typeof DashboardLayoutInventoryMovementsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/items/': {
      id: '/dashboard/_layout/inventory/items/'
      path: '/inventory/items'
      fullPath: '/dashboard/inventory/items/'
      preLoaderRoute: typeof DashboardLayoutInventoryItemsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/counts/': {
      id: '/dashboard/_layout/inventory/counts/'
      path: '/inventory/counts'
      fullPath: '/dashboard/inventory/counts/'
      preLoaderRoute: typeof DashboardLayoutInventoryCountsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/alerts/': {
      id: '/dashboard/_layout/inventory/alerts/'
      path: '/inventory/alerts'
      fullPath: '/dashboard/inventory/alerts/'
      preLoaderRoute: typeof DashboardLayoutInventoryAlertsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/menu/products/create': {
      id: '/dashboard/_layout/menu/products/create'
      path: '/menu/products/create'
      fullPath: '/dashboard/menu/products/create'
      preLoaderRoute: typeof DashboardLayoutMenuProductsCreateRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/writeoffs/$writeoffId': {
      id: '/dashboard/_layout/inventory/writeoffs/$writeoffId'
      path: '/inventory/writeoffs/$writeoffId'
      fullPath: '/dashboard/inventory/writeoffs/$writeoffId'
      preLoaderRoute: typeof DashboardLayoutInventoryWriteoffsWriteoffIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/suppliers/$supplierId': {
      id: '/dashboard/_layout/inventory/suppliers/$supplierId'
      path: '/inventory/suppliers/$supplierId'
      fullPath: '/dashboard/inventory/suppliers/$supplierId'
      preLoaderRoute: typeof DashboardLayoutInventorySuppliersSupplierIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/recipes/$recipeId': {
      id: '/dashboard/_layout/inventory/recipes/$recipeId'
      path: '/inventory/recipes/$recipeId'
      fullPath: '/dashboard/inventory/recipes/$recipeId'
      preLoaderRoute: typeof DashboardLayoutInventoryRecipesRecipeIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/purchase-orders/$orderId': {
      id: '/dashboard/_layout/inventory/purchase-orders/$orderId'
      path: '/inventory/purchase-orders/$orderId'
      fullPath: '/dashboard/inventory/purchase-orders/$orderId'
      preLoaderRoute: typeof DashboardLayoutInventoryPurchaseOrdersOrderIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/production/$productionId': {
      id: '/dashboard/_layout/inventory/production/$productionId'
      path: '/inventory/production/$productionId'
      fullPath: '/dashboard/inventory/production/$productionId'
      preLoaderRoute: typeof DashboardLayoutInventoryProductionProductionIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/items/$itemId': {
      id: '/dashboard/_layout/inventory/items/$itemId'
      path: '/inventory/items/$itemId'
      fullPath: '/dashboard/inventory/items/$itemId'
      preLoaderRoute: typeof DashboardLayoutInventoryItemsItemIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/counts/$countId': {
      id: '/dashboard/_layout/inventory/counts/$countId'
      path: '/inventory/counts/$countId'
      fullPath: '/dashboard/inventory/counts/$countId'
      preLoaderRoute: typeof DashboardLayoutInventoryCountsCountIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/halls/$hallId/floor-plan': {
      id: '/dashboard/_layout/halls/$hallId/floor-plan'
      path: '/halls/$hallId/floor-plan'
      fullPath: '/dashboard/halls/$hallId/floor-plan'
      preLoaderRoute: typeof DashboardLayoutHallsHallIdFloorPlanRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/menu/products/$productId/edit': {
      id: '/dashboard/_layout/menu/products/$productId/edit'
      path: '/menu/products/$productId/edit'
      fullPath: '/dashboard/menu/products/$productId/edit'
      preLoaderRoute: typeof DashboardLayoutMenuProductsProductIdEditRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/dashboard/_layout/inventory/purchase-orders/$orderId/receive': {
      id: '/dashboard/_layout/inventory/purchase-orders/$orderId/receive'
      path: '/receive'
      fullPath: '/dashboard/inventory/purchase-orders/$orderId/receive'
      preLoaderRoute: typeof DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRouteImport
      parentRoute: typeof DashboardLayoutInventoryPurchaseOrdersOrderIdRoute
    }
  }
}

interface DashboardLayoutInventoryPurchaseOrdersOrderIdRouteChildren {
  DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRoute: typeof DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRoute
}

const DashboardLayoutInventoryPurchaseOrdersOrderIdRouteChildren: DashboardLayoutInventoryPurchaseOrdersOrderIdRouteChildren =
  {
    DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRoute:
      DashboardLayoutInventoryPurchaseOrdersOrderIdReceiveRoute,
  }

const DashboardLayoutInventoryPurchaseOrdersOrderIdRouteWithChildren =
  DashboardLayoutInventoryPurchaseOrdersOrderIdRoute._addFileChildren(
    DashboardLayoutInventoryPurchaseOrdersOrderIdRouteChildren
  )

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutAnalyticsAlertsRoute: typeof DashboardLayoutAnalyticsAlertsRoute
  DashboardLayoutAnalyticsBranchesRoute: typeof DashboardLayoutAnalyticsBranchesRoute
  DashboardLayoutAnalyticsCategoriesRoute: typeof DashboardLayoutAnalyticsCategoriesRoute
  DashboardLayoutAnalyticsChannelsRoute: typeof DashboardLayoutAnalyticsChannelsRoute
  DashboardLayoutAnalyticsCustomersRoute: typeof DashboardLayoutAnalyticsCustomersRoute
  DashboardLayoutAnalyticsFinancialRoute: typeof DashboardLayoutAnalyticsFinancialRoute
  DashboardLayoutAnalyticsForecastingRoute: typeof DashboardLayoutAnalyticsForecastingRoute
  DashboardLayoutAnalyticsHeatmapRoute: typeof DashboardLayoutAnalyticsHeatmapRoute
  DashboardLayoutAnalyticsPaymentsRoute: typeof DashboardLayoutAnalyticsPaymentsRoute
  DashboardLayoutAnalyticsProductsRoute: typeof DashboardLayoutAnalyticsProductsRoute
  DashboardLayoutAnalyticsSalesRoute: typeof DashboardLayoutAnalyticsSalesRoute
  DashboardLayoutAnalyticsStaffRoute: typeof DashboardLayoutAnalyticsStaffRoute
  DashboardLayoutBranchesBranchIdRoute: typeof DashboardLayoutBranchesBranchIdRoute
  DashboardLayoutBranchesBulkImportRoute: typeof DashboardLayoutBranchesBulkImportRoute
  DashboardLayoutMenuAdditionsRoute: typeof DashboardLayoutMenuAdditionsRoute
  DashboardLayoutMenuBranchOverridesRoute: typeof DashboardLayoutMenuBranchOverridesRoute
  DashboardLayoutMenuCategoriesRoute: typeof DashboardLayoutMenuCategoriesRoute
  DashboardLayoutMenuModifiersRoute: typeof DashboardLayoutMenuModifiersRoute
  DashboardLayoutStaffEmployeesRoute: typeof DashboardLayoutStaffEmployeesRoute
  DashboardLayoutViewsViewIdRoute: typeof DashboardLayoutViewsViewIdRoute
  DashboardLayoutViewsNewRoute: typeof DashboardLayoutViewsNewRoute
  DashboardLayoutAnalyticsIndexRoute: typeof DashboardLayoutAnalyticsIndexRoute
  DashboardLayoutBranchesIndexRoute: typeof DashboardLayoutBranchesIndexRoute
  DashboardLayoutHallsIndexRoute: typeof DashboardLayoutHallsIndexRoute
  DashboardLayoutInventoryIndexRoute: typeof DashboardLayoutInventoryIndexRoute
  DashboardLayoutMenuIndexRoute: typeof DashboardLayoutMenuIndexRoute
  DashboardLayoutOverviewIndexRoute: typeof DashboardLayoutOverviewIndexRoute
  DashboardLayoutProfileIndexRoute: typeof DashboardLayoutProfileIndexRoute
  DashboardLayoutSettingsIndexRoute: typeof DashboardLayoutSettingsIndexRoute
  DashboardLayoutStaffIndexRoute: typeof DashboardLayoutStaffIndexRoute
  DashboardLayoutViewsIndexRoute: typeof DashboardLayoutViewsIndexRoute
  DashboardLayoutHallsHallIdFloorPlanRoute: typeof DashboardLayoutHallsHallIdFloorPlanRoute
  DashboardLayoutInventoryCountsCountIdRoute: typeof DashboardLayoutInventoryCountsCountIdRoute
  DashboardLayoutInventoryItemsItemIdRoute: typeof DashboardLayoutInventoryItemsItemIdRoute
  DashboardLayoutInventoryProductionProductionIdRoute: typeof DashboardLayoutInventoryProductionProductionIdRoute
  DashboardLayoutInventoryPurchaseOrdersOrderIdRoute: typeof DashboardLayoutInventoryPurchaseOrdersOrderIdRouteWithChildren
  DashboardLayoutInventoryRecipesRecipeIdRoute: typeof DashboardLayoutInventoryRecipesRecipeIdRoute
  DashboardLayoutInventorySuppliersSupplierIdRoute: typeof DashboardLayoutInventorySuppliersSupplierIdRoute
  DashboardLayoutInventoryWriteoffsWriteoffIdRoute: typeof DashboardLayoutInventoryWriteoffsWriteoffIdRoute
  DashboardLayoutMenuProductsCreateRoute: typeof DashboardLayoutMenuProductsCreateRoute
  DashboardLayoutInventoryAlertsIndexRoute: typeof DashboardLayoutInventoryAlertsIndexRoute
  DashboardLayoutInventoryCountsIndexRoute: typeof DashboardLayoutInventoryCountsIndexRoute
  DashboardLayoutInventoryItemsIndexRoute: typeof DashboardLayoutInventoryItemsIndexRoute
  DashboardLayoutInventoryMovementsIndexRoute: typeof DashboardLayoutInventoryMovementsIndexRoute
  DashboardLayoutInventoryProductionIndexRoute: typeof DashboardLayoutInventoryProductionIndexRoute
  DashboardLayoutInventoryPurchaseOrdersIndexRoute: typeof DashboardLayoutInventoryPurchaseOrdersIndexRoute
  DashboardLayoutInventoryRecipesIndexRoute: typeof DashboardLayoutInventoryRecipesIndexRoute
  DashboardLayoutInventoryStockIndexRoute: typeof DashboardLayoutInventoryStockIndexRoute
  DashboardLayoutInventorySuppliersIndexRoute: typeof DashboardLayoutInventorySuppliersIndexRoute
  DashboardLayoutInventoryWarehousesIndexRoute: typeof DashboardLayoutInventoryWarehousesIndexRoute
  DashboardLayoutInventoryWriteoffsIndexRoute: typeof DashboardLayoutInventoryWriteoffsIndexRoute
  DashboardLayoutMenuProductsIndexRoute: typeof DashboardLayoutMenuProductsIndexRoute
  DashboardLayoutMenuProductsProductIdEditRoute: typeof DashboardLayoutMenuProductsProductIdEditRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutAnalyticsAlertsRoute: DashboardLayoutAnalyticsAlertsRoute,
  DashboardLayoutAnalyticsBranchesRoute: DashboardLayoutAnalyticsBranchesRoute,
  DashboardLayoutAnalyticsCategoriesRoute:
    DashboardLayoutAnalyticsCategoriesRoute,
  DashboardLayoutAnalyticsChannelsRoute: DashboardLayoutAnalyticsChannelsRoute,
  DashboardLayoutAnalyticsCustomersRoute:
    DashboardLayoutAnalyticsCustomersRoute,
  DashboardLayoutAnalyticsFinancialRoute:
    DashboardLayoutAnalyticsFinancialRoute,
  DashboardLayoutAnalyticsForecastingRoute:
    DashboardLayoutAnalyticsForecastingRoute,
  DashboardLayoutAnalyticsHeatmapRoute: DashboardLayoutAnalyticsHeatmapRoute,
  DashboardLayoutAnalyticsPaymentsRoute: DashboardLayoutAnalyticsPaymentsRoute,
  DashboardLayoutAnalyticsProductsRoute: DashboardLayoutAnalyticsProductsRoute,
  DashboardLayoutAnalyticsSalesRoute: DashboardLayoutAnalyticsSalesRoute,
  DashboardLayoutAnalyticsStaffRoute: DashboardLayoutAnalyticsStaffRoute,
  DashboardLayoutBranchesBranchIdRoute: DashboardLayoutBranchesBranchIdRoute,
  DashboardLayoutBranchesBulkImportRoute:
    DashboardLayoutBranchesBulkImportRoute,
  DashboardLayoutMenuAdditionsRoute: DashboardLayoutMenuAdditionsRoute,
  DashboardLayoutMenuBranchOverridesRoute:
    DashboardLayoutMenuBranchOverridesRoute,
  DashboardLayoutMenuCategoriesRoute: DashboardLayoutMenuCategoriesRoute,
  DashboardLayoutMenuModifiersRoute: DashboardLayoutMenuModifiersRoute,
  DashboardLayoutStaffEmployeesRoute: DashboardLayoutStaffEmployeesRoute,
  DashboardLayoutViewsViewIdRoute: DashboardLayoutViewsViewIdRoute,
  DashboardLayoutViewsNewRoute: DashboardLayoutViewsNewRoute,
  DashboardLayoutAnalyticsIndexRoute: DashboardLayoutAnalyticsIndexRoute,
  DashboardLayoutBranchesIndexRoute: DashboardLayoutBranchesIndexRoute,
  DashboardLayoutHallsIndexRoute: DashboardLayoutHallsIndexRoute,
  DashboardLayoutInventoryIndexRoute: DashboardLayoutInventoryIndexRoute,
  DashboardLayoutMenuIndexRoute: DashboardLayoutMenuIndexRoute,
  DashboardLayoutOverviewIndexRoute: DashboardLayoutOverviewIndexRoute,
  DashboardLayoutProfileIndexRoute: DashboardLayoutProfileIndexRoute,
  DashboardLayoutSettingsIndexRoute: DashboardLayoutSettingsIndexRoute,
  DashboardLayoutStaffIndexRoute: DashboardLayoutStaffIndexRoute,
  DashboardLayoutViewsIndexRoute: DashboardLayoutViewsIndexRoute,
  DashboardLayoutHallsHallIdFloorPlanRoute:
    DashboardLayoutHallsHallIdFloorPlanRoute,
  DashboardLayoutInventoryCountsCountIdRoute:
    DashboardLayoutInventoryCountsCountIdRoute,
  DashboardLayoutInventoryItemsItemIdRoute:
    DashboardLayoutInventoryItemsItemIdRoute,
  DashboardLayoutInventoryProductionProductionIdRoute:
    DashboardLayoutInventoryProductionProductionIdRoute,
  DashboardLayoutInventoryPurchaseOrdersOrderIdRoute:
    DashboardLayoutInventoryPurchaseOrdersOrderIdRouteWithChildren,
  DashboardLayoutInventoryRecipesRecipeIdRoute:
    DashboardLayoutInventoryRecipesRecipeIdRoute,
  DashboardLayoutInventorySuppliersSupplierIdRoute:
    DashboardLayoutInventorySuppliersSupplierIdRoute,
  DashboardLayoutInventoryWriteoffsWriteoffIdRoute:
    DashboardLayoutInventoryWriteoffsWriteoffIdRoute,
  DashboardLayoutMenuProductsCreateRoute:
    DashboardLayoutMenuProductsCreateRoute,
  DashboardLayoutInventoryAlertsIndexRoute:
    DashboardLayoutInventoryAlertsIndexRoute,
  DashboardLayoutInventoryCountsIndexRoute:
    DashboardLayoutInventoryCountsIndexRoute,
  DashboardLayoutInventoryItemsIndexRoute:
    DashboardLayoutInventoryItemsIndexRoute,
  DashboardLayoutInventoryMovementsIndexRoute:
    DashboardLayoutInventoryMovementsIndexRoute,
  DashboardLayoutInventoryProductionIndexRoute:
    DashboardLayoutInventoryProductionIndexRoute,
  DashboardLayoutInventoryPurchaseOrdersIndexRoute:
    DashboardLayoutInventoryPurchaseOrdersIndexRoute,
  DashboardLayoutInventoryRecipesIndexRoute:
    DashboardLayoutInventoryRecipesIndexRoute,
  DashboardLayoutInventoryStockIndexRoute:
    DashboardLayoutInventoryStockIndexRoute,
  DashboardLayoutInventorySuppliersIndexRoute:
    DashboardLayoutInventorySuppliersIndexRoute,
  DashboardLayoutInventoryWarehousesIndexRoute:
    DashboardLayoutInventoryWarehousesIndexRoute,
  DashboardLayoutInventoryWriteoffsIndexRoute:
    DashboardLayoutInventoryWriteoffsIndexRoute,
  DashboardLayoutMenuProductsIndexRoute: DashboardLayoutMenuProductsIndexRoute,
  DashboardLayoutMenuProductsProductIdEditRoute:
    DashboardLayoutMenuProductsProductIdEditRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteRoute: InviteRoute,
  StaffInviteRoute: StaffInviteRoute,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  OnboardingBranchSetupRoute: OnboardingBranchSetupRoute,
  OnboardingBusinessInfoRoute: OnboardingBusinessInfoRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingMenuTemplateRoute: OnboardingMenuTemplateRoute,
  OnboardingStaffInviteRoute: OnboardingStaffInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
